package br.com.golfinvest.data.view;

import org.springframework.jdbc.core.JdbcTemplate;

import javax.swing.*;
import java.awt.*;

public class Capitao extends JFrame {

    private JdbcTemplate jdbcTemplate;
    private JPanel capitaoRootPanel;

    public Capitao(String title, JdbcTemplate jdbcTemplatePassed) {
        super();
        title = title + " - (Registro de capitão de produto no banco de dados)";
        setTitle(title);
        setSize(1000, 600);
        jdbcTemplate = jdbcTemplatePassed;

        initComponents();
        regEvents();
    }

    public void initComponents() {
        System.out.println("Init Components Capitao...");
        setContentPane(capitaoRootPanel);

        setVisible(true);
    }

    public void regEvents() {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        capitaoRootPanel = new JPanel();
        capitaoRootPanel.setLayout(new BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return capitaoRootPanel;
    }
}
